### ISSUE TITLE
miao-plugin 2.5.5

### ISSUE THREAD

**Issue by rukiuss1** [117503445/yunzai-bot-web#37]
miao-plugin已安装。安装后更新面板时，出现以下错误消息，如何解决？
[YzBot][15:46:45.493][ERRO] [喵喵:角色面板][profileRefresh]
[YzBot][15:46:45.494][ERRO] TypeError: e.runtime?.user?.getCkUidList is not a function
    at Object.render (file:///workspace/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileList.js:60:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cls.refresh (file:///workspace/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileList.js:39:16)
    at async cls.<computed> [as profileRefresh] (file:///workspace/Yunzai-Bot/plugins/miao-plugin/components/App.js:96:18)
    at async PluginsLoader.deal (file:///workspace/Yunzai-Bot/lib/plugins/loader.js:251:52)
    at async Object.<anonymous> (file:///workspace/Yunzai-Bot/lib/tools/server.js:155:9)

**Comment by 117503445** [comment]
你是怎么更新面板的呀
